// Write one static HTML redirect page into public/ for each entry in
// _data/redirects.yaml, so the old Jekyll URLs keep working on GitHub Pages,
// which can't send real HTTP redirects. Runs as `prebuild`; run it alone with
// `npm run redirects`. The output is gitignored.
//
// Usage: tsx scripts/generate-redirects.ts

import fs from "fs";
import path from "path";
import { getPostBySlug, getRedirects, postsDirectory } from "@/lib/api";
import site, { absoluteUrl } from "@/lib/site";
import { Redirect } from "@/types";

// Marks files this script owns, so it never overwrites a hand-written file
// in public/.
const GENERATED_MARKER = "<!-- generated by scripts/generate-redirects.ts -->";

const publicDirectory = path.join(process.cwd(), "public");

interface SocialMeta {
  title: string;
  description?: string;
  image?: string;
}

interface ResolvedPage {
  destination: string;
  canonical?: string;
  noindex: boolean;
  meta?: SocialMeta;
}

const validateRedirect = (entry: Redirect, index: number) => {
  const label = `redirect #${index + 1} (from: ${entry.from})`;
  const fix = "fix it in _data/redirects.yaml";

  if (typeof entry.from !== "string" || !entry.from.startsWith("/")) {
    throw new Error(`${label}: \`from\` must start with "/"; ${fix}`);
  }
  if (entry.from.endsWith("/")) {
    throw new Error(`${label}: \`from\` must not end with "/"; ${fix}`);
  }

  const destinationKeys = ["post", "page", "link"].filter(
    (key) => key in entry,
  );
  if (destinationKeys.length !== 1) {
    throw new Error(
      `${label}: needs exactly one of post/page/link, found ${destinationKeys.length}; ${fix}`,
    );
  }

  if ("page" in entry && !entry.page.startsWith("/")) {
    throw new Error(`${label}: \`page\` must start with "/"; ${fix}`);
  }
  if ("link" in entry && !entry.link.startsWith("https://")) {
    throw new Error(`${label}: \`link\` must start with "https://"; ${fix}`);
  }
};

// GitHub Pages serves /x from x.html, so an extensionless path gets .html.
const outputPath = (from: string) =>
  path.join(publicDirectory, from.endsWith(".html") ? from : `${from}.html`);

const resolvePage = async (
  entry: Redirect,
  postFilenames: string[],
): Promise<ResolvedPage> => {
  if ("post" in entry) {
    // An exact match against the directory listing, because macOS would
    // accept a slug with the wrong case and the deployed URL would 404.
    if (!postFilenames.includes(`${entry.post}.md`)) {
      throw new Error(
        `redirect from ${entry.from} names post ${entry.post}, which doesn't exist in _data/posts/; fix the slug in _data/redirects.yaml`,
      );
    }

    const { metadata } = await getPostBySlug(entry.post);
    const destination = `/posts/${entry.post}`;

    return {
      destination,
      canonical: absoluteUrl(destination),
      noindex: false,
      meta: {
        title: metadata.title,
        description: metadata.blurb,
        image: metadata.splashImageSource
          ? absoluteUrl(metadata.splashImageSource)
          : undefined,
      },
    };
  }

  if ("page" in entry) {
    return {
      destination: entry.page,
      canonical: absoluteUrl(entry.page),
      noindex: false,
    };
  }

  return { destination: entry.link, noindex: true };
};

const escapeHtml = (text: string) =>
  text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");

// JSON.stringify doesn't escape "</script>", which would end the tag early.
const toScriptString = (text: string) =>
  JSON.stringify(text).replace(/</g, "\\u003c");

const renderSocialMeta = (
  { title, description, image }: SocialMeta,
  url?: string,
) =>
  [
    description &&
      `<meta name="description" content="${escapeHtml(description)}">`,
    `<meta property="og:type" content="article">`,
    url && `<meta property="og:url" content="${escapeHtml(url)}">`,
    `<meta property="og:title" content="${escapeHtml(title)}">`,
    description &&
      `<meta property="og:description" content="${escapeHtml(description)}">`,
    image && `<meta property="og:image" content="${escapeHtml(image)}">`,
    `<meta name="twitter:card" content="${image ? "summary_large_image" : "summary"}">`,
  ]
    .filter(Boolean)
    .join("\n");

// Best effort: the redirect below doesn't wait for it, so a visit is only
// counted when gtag sends before the page unloads.
const renderAnalytics = () => {
  const id = site.googleAnalyticsId;
  return `<script async src="https://www.googletagmanager.com/gtag/js?id=${id}"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', ${toScriptString(id)});
</script>`;
};

const renderPage = ({ destination, canonical, noindex, meta }: ResolvedPage) =>
  `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
${GENERATED_MARKER}
<title>${escapeHtml(meta?.title ?? "Redirecting…")}</title>
<meta http-equiv="refresh" content="0; url=${escapeHtml(destination)}">
${canonical ? `<link rel="canonical" href="${escapeHtml(canonical)}">` : ""}
${noindex ? `<meta name="robots" content="noindex">` : ""}
${meta ? renderSocialMeta(meta, canonical) : ""}
${renderAnalytics()}
<script>location.replace(${toScriptString(destination)})</script>
</head>
<body>
<p>This page has moved to <a href="${escapeHtml(destination)}">${escapeHtml(destination)}</a>.</p>
</body>
</html>
`.replace(/\n{2,}/g, "\n");

const main = async () => {
  const redirects = getRedirects();
  const postFilenames = fs.readdirSync(postsDirectory);

  // Validate and resolve everything before writing, so one bad entry leaves
  // public/ untouched.
  const seen = new Set<string>();
  const pages: { file: string; html: string }[] = [];
  for (let index = 0; index < redirects.length; index++) {
    const entry = redirects[index];
    validateRedirect(entry, index);
    if (seen.has(entry.from)) {
      throw new Error(
        `redirect from ${entry.from} is listed twice; remove one from _data/redirects.yaml`,
      );
    }
    seen.add(entry.from);

    const file = outputPath(entry.from);
    if (
      fs.existsSync(file) &&
      !fs.readFileSync(file, "utf8").includes(GENERATED_MARKER)
    ) {
      throw new Error(
        `${path.relative(process.cwd(), file)} exists and wasn't generated by this script; remove it or change \`from\` in _data/redirects.yaml`,
      );
    }

    pages.push({
      file,
      html: renderPage(await resolvePage(entry, postFilenames)),
    });
  }

  for (const { file, html } of pages) {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, html);
  }
};

main();
